### ISSUE TITLE
Support for other microphones.

### ISSUE THREAD

**Issue by arnoldandreasson** [cloudedbats/cloudedbats_wurb_2020#24]
I should be possible to use other microphones as long as they can be identifies by ALSA (https://en.wikipedia.org/wiki/Advanced_Linux_Sound_Architecture). Run this command from inside the virtual python environment, venv, to check that: "python3 -m sounddevice". 

Some new configuration options is needed to do that. Until then, these code modifications in version 0.8.0 can be used for test:
- wurb_manager.py: Replace the limit in row 100: "if (len(device_name) > 1) and sampling_freq_hz > 180000:"
- wurb_recorder.py: Extend the list in row 29 (example with "GoMic"): "self.name_part_list = ["Pettersson", "UltraMic", "GoMic"]"
- wurb_recorder.py: Use another hardcoded value in row 105 if you want to change the default frequency (example for GoMic running on 20000 instead of 44100 kHz): "self.sampling_freq_hz = 20000 # sampling_freq_hz"

And don't forget to change the sound detection limit in the WURB settings if a non-ultrasonic mic is used.

**Comment by duncanhoyle** [comment]
I've successfully modified the code locally to work with an AudioInjector-Ultra soud card (http://www.audioinjector.net/rpi-ultra).
For line 29 the card identifies itself as 'audioinjector-ultra'
Sadly when queried, it's default sample rate is 44100 so I had to hard code the rate to 192khz (it's maximum)

**Comment by arnoldandreasson** [comment]
Thank you Duncan for reporting this. I have got reports via mail that "Wolfson Pi Audio Card" also works with similar modifications. In the development version I have moved all needed modifications to a single place in the code. Check for this in "wurb_rec/wurb_recorder.py":
            # Check if another ALSA mic. is specified in advanced settings.
            if not device_name:
                settings_device_name_part = "GoMic"  # TODO: From settings.
                settings_sampling_freq_hz = 0  # TODO: From settings.
                # settings_sampling_freq_hz = 44100  # TODO: From settings.

In the 0.9.0 release these values will be added to a new section with "advanced settings" and no code modifications is then needed.

**Comment by Dutchblue020** [comment]
Hi,

I want to test it with my own USB mic (ok i know no ultrasonic mic. but want first test if it's work with other sounds).
I have an USB mic. that can be found inside the Pi
`
Bus 001 Device 003: ID 8086:0808 Intel Corp.
`
`
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`
But how can I use the mic as input?

**Comment by arnoldandreasson** [comment]
Hi Dutchblue020, 
In next release, version 0.9.0, this will be possible to do by using ordinary settings. In current "master"-branch this is described in the comment above. The "GoMic" I used there for test is also a non-ultrasonic mic. That means that you have to replace "GoMic" with a unique substring from your device in the "wurb_rec/wurb_recorder.py" to test it now. Please contact me at info@cloudedbats.org if it does not  work. Don't forget to change the frequency limit for automatic detection when not using it for ultrasound.

**Comment by arnoldandreasson** [comment]
Support for environment variables:
- WURB_INPUT_DEVICE, default "HiFiBerry".
- WURB_INPUT_DEVICE_FREQ_HZ, default 0 (=automatic).
Ready for test.

**Comment by arnoldandreasson** [comment]
Check the startup script "wurb_rec_start.sh" for environment variables.

**Comment by arnoldandreasson** [comment]
Version 0.9.0 released.
