### ISSUE TITLE
Stability problems with RaspiOS Lite 2021-01-11

### ISSUE THREAD

**Issue by arnoldandreasson** [cloudedbats/cloudedbats_wurb_2020#34]
There are problems when audio feedback is activated and the detector can stop responding. Temporary solution: Turn audio feedback "Off" (under Settings - More).

PulseAudio was introduced in the december release (https://www.raspberrypi.org/blog/new-raspberry-pi-os-release-december-2020/). Audio feedback was working with the december release but not with the januari release of RaspiOS Lite.

There must be some conflicts and I will try to replace the usage of python-sounddevice with a pure ALSA implementation when accessing microphones and headphone for audio feedback.

**Comment by arnoldandreasson** [comment]
The move from sounddevice to ALSA is done and checked in to the "development" branch. It seems like this move solved the stability problems and the implementation is much cleaner, for example libportaudio2 is not needed any longer. Hopefully this also works better together with PulseAudio.
There still are some work to be done in the code for M500 and HiFiBerry as well as for logging and error handling, but initial tests are promising.

**Comment by arnoldandreasson** [comment]
HiFiBerry problems are fixed and it seems to be more stable with a clean collaboration between asynchio and alsaaudio where there are no callbacks from the sound lib.

Ready for test.

**Comment by arnoldandreasson** [comment]
Version 0.9.0 released.

**Comment by slowglow** [comment]
I am a bit disappointed to see sounddevice go. I like that it is cross-platform, well documented and easier to use than some of the alternatives. I looked around and it seems that sounddevice playback it is a common problem on recent Raspberry Pi OS:
https://www.raspberrypi.org/forums/viewtopic.php?t=280156

**Comment by arnoldandreasson** [comment]
Hi, I have no plans to go back to sounddevice. It's true that I lost the cross-platform part, but there was many problems with sounddevice. One was that I want plug-and-play for the mics and to do that there was an ugly reset needed that didn't work when I added audio feedback. Another problem was that the callback mechanism didn't work well with asynchio and the whole web server was blocked.  Pyalsaaudio is a really thin layer on top of ALSA that gives me more control compared to use both the layers of sounddevice and libportaudio2.

**Comment by slowglow** [comment]
Thanks for the explanation. Great piece of work by the way.
